---
- hosts: ios
  gather_facts: no

  vars:
  
    dns_servers:
      - ip name-server 8.8.8.8
      - ip name-server 8.8.4.4
      
      
  tasks:

  - name: set name-server commands
    with_items: "{{ dns_servers }}"
    ios_config:
      lines:
        - "{{ item }}"
    register: set_dns
